switched to uglifier from yui added DEBUG param to make compilation

diff --git a/marklet/Makefile b/marklet/Makefile
--- a/marklet/Makefile
+++ b/marklet/Makefile
@@ -1,6 +1,15 @@
 all: clean concatenate build
 
+
+define DEBUG_CHECK
+    @if [ -z $(DEBUG) ]; then \
+        echo "\nArgument required: pass DEBUG=false for no console, DEBUG=true for console output\n"; \
+	exit 1; \
+    fi;
+endef
+
 concatenate:
+	$(DEBUG_CHECK)
 #	cat *.js > ./bin/stereopaw.js
 	cat stereopaw.js >> ./bin/stereopaw.js
 	cat Util.js >> ./bin/stereopaw.js
@@ -11,7 +20,8 @@ concatenate:
 	cat Run.js >> ./bin/stereopaw.js
 
 build:
-	java -jar ./lib/yuicompressor-2.4.8.jar -o ./bin/stereopaw-min.js ./bin/*.js
+#	java -jar ./lib/yuicompressor-2.4.8.jar -o ./bin/stereopaw-min.js ./bin/*.js
+	uglifyjs ./bin/stereopaw.js -o ./bin/stereopaw-min.js --compress -d DEBUG=$(DEBUG)
 	rm ./bin/stereopaw.js
 	mv ./bin/stereopaw-min.js ../app/public/
 
