Conditional compilation with host for dev vs production

diff --git a/marklet/Makefile b/marklet/Makefile
--- a/marklet/Makefile
+++ b/marklet/Makefile
@@ -1,15 +1,30 @@
-all: clean concatenate build
-
 
 define DEBUG_CHECK
     @if [ -z $(DEBUG) ]; then \
-        echo "\nArgument required: pass DEBUG=false for no console, DEBUG=true for console output\n"; \
+        echo "\n Argument required: pass DEBUG=false for no console, DEBUG=true for console output \n"; \
 	exit 1; \
     fi;
 endef
 
+define ENV_CHECK
+    @if [ -z $(ENV) ]; then \
+        echo "\n Argument required: dev --> ENV=0  / prod --> ENV=1 \n"; \
+	exit 1; \
+    fi;
+endef
+
+
+#ifeq ($(ENV), dev)
+#	HOST=
+#else
+#	HOST=
+#endif
+
+all: clean concatenate build
+
 concatenate:
 	$(DEBUG_CHECK)
+	$(ENV_CHECK)
 #	cat *.js > ./bin/stereopaw.js
 	cat stereopaw.js >> ./bin/stereopaw.js
 	cat Util.js >> ./bin/stereopaw.js
@@ -21,7 +36,7 @@ concatenate:
 
 build:
 #	java -jar ./lib/yuicompressor-2.4.8.jar -o ./bin/stereopaw-min.js ./bin/*.js
-	uglifyjs ./bin/stereopaw.js -o ./bin/stereopaw-min.js --compress -d DEBUG=$(DEBUG)
+	uglifyjs ./bin/stereopaw.js -o ./bin/stereopaw-min.js --compress -d "DEBUG=$(DEBUG),ENV=$(ENV)"
 	rm ./bin/stereopaw.js
 	mv ./bin/stereopaw-min.js ../app/public/
 
